#ifndef GAMEPAD_H_
#define GAMEPAD_H_

namespace wvn::inp
{
	constexpr unsigned MAX_GAMEPADS = 4;

	enum GamepadButton
	{
		GAMEPAD_BTN_NONE = -1,

		GAMEPAD_BTN_A,
		GAMEPAD_BTN_B,
		GAMEPAD_BTN_X,
		GAMEPAD_BTN_Y,

		GAMEPAD_BTN_BACK,
		GAMEPAD_BTN_SELECT,
		GAMEPAD_BTN_START,

		GAMEPAD_BTN_LEFT_STICK,
		GAMEPAD_BTN_RIGHT_STICK,

		GAMEPAD_BTN_LEFT_SHOULDER,
		GAMEPAD_BTN_RIGHT_SHOULDER,

		GAMEPAD_BTN_UP,
		GAMEPAD_BTN_DOWN,
		GAMEPAD_BTN_LEFT,
		GAMEPAD_BTN_RIGHT,

		GAMEPAD_BTN_MAX_ENUM
	};

	enum GamepadAxis
	{
		GAMEPAD_AXIS_NONE = -1,

		GAMEPAD_AXIS_LEFT_X,
		GAMEPAD_AXIS_LEFT_Y,

		GAMEPAD_AXIS_RIGHT_X,
		GAMEPAD_AXIS_RIGHT_Y,

		GAMEPAD_AXIS_TRIGGER_LEFT,
		GAMEPAD_AXIS_TRIGGER_RIGHT,

		GAMEPAD_AXIS_MAX_ENUM
	};

	enum GamepadType
	{
		GAMEPAD_TYPE_UNKNOWN = 0,
		GAMEPAD_TYPE_STANDARD,

		GAMEPAD_TYPE_XBOX_360,
		GAMEPAD_TYPE_XBOX_ONE,

		GAMEPAD_TYPE_PS3,
		GAMEPAD_TYPE_PS4,
		GAMEPAD_TYPE_PS5,

		GAMEPAD_TYPE_NINTENDO_SWITCH_PRO,
		GAMEPAD_TYPE_NINTENDO_SWITCH_JOYCON_LEFT,
		GAMEPAD_TYPE_NINTENDO_SWITCH_JOYCON_RIGHT,
		GAMEPAD_TYPE_NINTENDO_SWITCH_JOYCON_PAIR,

		GAMEPAD_TYPE_MAX_ENUM
	};
}

#endif // GAMEPAD_H_
